USE [WHODDE]
GO

/****** Object:  Table [dbo].[ATC]    Script Date: 12/30/2015 12:40:09 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ATC](
	[ATCCode] [varchar](10) NOT NULL,
	[Level] [varchar](1) NULL,
	[Text] [varchar](110) NULL,
 CONSTRAINT [PK_ATC] PRIMARY KEY CLUSTERED 
(
	[ATCCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

