--truncate table  [WHODDE].[dbo].[MP]

--BULK INSERT [WHODDE].[dbo].[MP] FROM 'C:\WHODD\MP.txt' WITH (FORMATFILE = 'C:\WHODD\MP.xml', ROWTERMINATOR='\r\n');
--BULK INSERT [WHODDE].[dbo].[PP] FROM 'C:\WHODD\PP.txt' WITH (FORMATFILE = 'C:\WHODD\PP.xml', ROWTERMINATOR='\r\n');
--BULK INSERT [WHODDE].[dbo].[THG] FROM 'C:\WHODD\SRCE.txt' WITH (FORMATFILE = 'C:\WHODD\THG.xml', ROWTERMINATOR='\r\n');
--BULK INSERT [WHODDE].[dbo].[ING] FROM 'C:\WHODD\SRCE.txt' WITH (FORMATFILE = 'C:\WHODD\ING.xml', ROWTERMINATOR='\r\n');
--BULK INSERT [WHODDE].[dbo].[SRCE] FROM 'C:\WHODD\SRCE.txt' WITH (FORMATFILE = 'C:\WHODD\SRCE.xml', ROWTERMINATOR='\r\n');


--SELECT  * FROM OPENROWSET(BULK 'C:\WHODD\MP.txt', FORMATFILE ='C:\WHODD\MP.xml') T
--SELECT  * FROM OPENROWSET(BULK 'C:\WHODD\PP.txt', FORMATFILE ='C:\WHODD\PP.xml') T
--SELECT  * FROM OPENROWSET(BULK 'C:\WHODD\THG.txt', FORMATFILE ='C:\WHODD\THG.xml') T
--SELECT  * FROM OPENROWSET(BULK 'C:\WHODD\ING.txt', FORMATFILE ='C:\WHODD\ING.xml') T
--SELECT  * FROM OPENROWSET(BULK 'C:\WHODD\SRCE.txt', FORMATFILE ='C:\WHODD\SRCE.xml') T
