/*

ING Table

*/

USE [WHODDE]

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ING]  WITH CHECK ADD  CONSTRAINT [FK_ING_MP] FOREIGN KEY([Medicinalprod_Id])
REFERENCES [dbo].[MP] ([Medicinalprod_Id])
GO

ALTER TABLE [dbo].[ING] CHECK CONSTRAINT [FK_ING_MP]
GO

ALTER TABLE [dbo].[ING]  WITH CHECK ADD  CONSTRAINT [FK_ING_PP] FOREIGN KEY([Pharmproduct_Id])
REFERENCES [dbo].[PP] ([Pharmproduct_Id])
GO

ALTER TABLE [dbo].[ING] CHECK CONSTRAINT [FK_ING_PP]
GO

ALTER TABLE [dbo].[ING]  WITH CHECK ADD  CONSTRAINT [FK_ING_SUN] FOREIGN KEY([Substance_Id])
REFERENCES [dbo].[SUN] ([Substance_Id])
GO

ALTER TABLE [dbo].[ING] CHECK CONSTRAINT [FK_ING_SUN]
GO

ALTER TABLE [dbo].[ING]  WITH CHECK ADD  CONSTRAINT [FK_ING_UNIT] FOREIGN KEY([Unit])
REFERENCES [dbo].[UNIT] ([Unit_Id])
GO

ALTER TABLE [dbo].[ING] CHECK CONSTRAINT [FK_ING_UNIT]
GO

ALTER TABLE [dbo].[ING]  WITH CHECK ADD  CONSTRAINT [FK_ING_Unit-L] FOREIGN KEY([Unit])
REFERENCES [dbo].[Unit-L] ([Unit_Id])
GO

ALTER TABLE [dbo].[ING] CHECK CONSTRAINT [FK_ING_Unit-L]
GO

ALTER TABLE [dbo].[ING]  WITH CHECK ADD  CONSTRAINT [FK_ING_Unit-X] FOREIGN KEY([Unit])
REFERENCES [dbo].[Unit-X] ([Unit_Id])
GO

ALTER TABLE [dbo].[ING] CHECK CONSTRAINT [FK_ING_Unit-X]
GO

/*

 MP
*/


ALTER TABLE [dbo].[MP]  WITH CHECK ADD  CONSTRAINT [FK_MP_CCODE] FOREIGN KEY([SourceCountry])
REFERENCES [dbo].[CCODE] ([CountryCode])
GO

ALTER TABLE [dbo].[MP] CHECK CONSTRAINT [FK_MP_CCODE]
GO

ALTER TABLE [dbo].[MP]  WITH CHECK ADD  CONSTRAINT [FK_MP_ORG] FOREIGN KEY([Company])
REFERENCES [dbo].[ORG] ([Organization_Id])
GO

ALTER TABLE [dbo].[MP] CHECK CONSTRAINT [FK_MP_ORG]
GO

ALTER TABLE [dbo].[MP]  WITH CHECK ADD  CONSTRAINT [FK_MP_PRG] FOREIGN KEY([ProductGroup])
REFERENCES [dbo].[PRG] ([Productgroup_Id])
GO

ALTER TABLE [dbo].[MP] CHECK CONSTRAINT [FK_MP_PRG]
GO

ALTER TABLE [dbo].[MP]  WITH CHECK ADD  CONSTRAINT [FK_MP_PRT] FOREIGN KEY([ProductType])
REFERENCES [dbo].[PRT] ([Prodtype_Id])
GO

ALTER TABLE [dbo].[MP] CHECK CONSTRAINT [FK_MP_PRT]
GO

/*
*    PP       
*/



ALTER TABLE [dbo].[PP]  WITH CHECK ADD  CONSTRAINT [FK_PP_MP] FOREIGN KEY([Medicinalprod_Id])
REFERENCES [dbo].[MP] ([Medicinalprod_Id])
GO

ALTER TABLE [dbo].[PP] CHECK CONSTRAINT [FK_PP_MP]
GO

ALTER TABLE [dbo].[PP]  WITH CHECK ADD  CONSTRAINT [FK_PP_PF] FOREIGN KEY([PharmaceuticalForm])
REFERENCES [dbo].[PF] ([Pharmform_Id])
GO

ALTER TABLE [dbo].[PP] CHECK CONSTRAINT [FK_PP_PF]
GO

/*
*		SUN
*/

ALTER TABLE [dbo].[SUN]  WITH CHECK ADD  CONSTRAINT [FK_SUN_SRCE] FOREIGN KEY([ReferenceCode])
REFERENCES [dbo].[SRCE] ([ReferenceCode])
GO

ALTER TABLE [dbo].[SUN] CHECK CONSTRAINT [FK_SUN_SRCE]
GO

/*
*		THG
*/



ALTER TABLE [dbo].[ThG]  WITH NOCHECK ADD  CONSTRAINT [FK_ThG_ATC] FOREIGN KEY([ATCCode])
REFERENCES [dbo].[ATC] ([ATCCode])
GO

ALTER TABLE [dbo].[ThG] CHECK CONSTRAINT [FK_ThG_ATC]
GO

ALTER TABLE [dbo].[ThG]  WITH NOCHECK ADD  CONSTRAINT [FK_ThG_MP] FOREIGN KEY([Medicinalprod_Id])
REFERENCES [dbo].[MP] ([Medicinalprod_Id])
GO

ALTER TABLE [dbo].[ThG] CHECK CONSTRAINT [FK_ThG_MP]
GO

