USE [WHODDE]
GO

/****** Object:  Table [dbo].[Unit-X]    Script Date: 12/30/2015 2:22:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Unit-X](
	[Unit_Id] [varchar](10) NOT NULL,
	[Text] [varchar](40) NULL,
 CONSTRAINT [PK_Unit-X] PRIMARY KEY CLUSTERED 
(
	[Unit_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

